config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks do
    put :sort, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
	validates_presence_of :title, :description

  	default_scope { order("priority ASC") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	  def index
	    @tasks = Task.all
	  end

	  def new
	    @task = Task.new
	  end

	  def create
	    @task = Task.create(task_params)
	    if @task.save
	      redirect_to root_path, notice: 'Task saved successfully'
	    else
	      render 'new'
	    end
	  end

	  def show

	  end

	  def sort
	    params[:order].each do |key,value|
	      Task.find(value[:id]).update_attribute(:priority,value[:position])
	    end
	    render :nothing => true
	  end

	  private

	  def task_params
	    params.require(:task).permit(:title,:description)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SortableList</title>
    <%= csrf_meta_tags %>
	<%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Sortable Lists</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav pull-right">
            <li class="active"><%= link_to "Home", root_path %></li>
            <li><%= link_to "Tutorial", "http://josephndungu.com/tutorials/ajax-sortable-lists-rails-4" %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_task.html.erb
<!-- adding data-id attribute -->
<div class="panel panel-default" data-id="<%= task.id %>">
  <div class="panel-heading">
    <h3 class="panel-title"><%= task.title %></h3>
  </div>
  <div class="panel-body">
    <%= truncate task.description, length: 50 %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-md-5 col-md-offset-4 sortable">
    <% if @tasks.any? %>
        <%= render @tasks %>
    <% else %>
    <p>No tasks found <%= link_to "Create Task", new_task_path %></p>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Create Task</h1>
    <%= form_for @task do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control", rows: 4 %>
        </div>
        <%= f.submit "Create Task", class: "btn btn-success" %>
    <% end %>
  </div>
</div>